@host = http://127.0.0.1:8888

### test /form
POST {{host}}/form  HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=andy&age=14

### test /json
POST {{host}}/json  HTTP/1.1
Content-Type: application/json

{
  "name": "andy",
  "age": 14
}